WIP: Add optional tasks for host types
cki-project/kpet-archived pull request #122
Opened 2019-11-15 13:24 UTC by emanchado

In some cases, certain host types need extra tasks in the generated
Beaker XML. This change adds an optional attribute "tasks" for host
types, which should be a Jinja2 template path specifying the extra
<task> elements to copy in the Beaker XML.

Ref. FASTMOVING-1398

2019-11-15 13:34 UTC, spbnick requested changes
Just two minor requests, otherwise looks perfectly reasonable :)

2019-11-15 13:34 UTC, spbnick commented on tests/test_integration_misc.py
> +                      host_type_regex: normal
You don't need to specify `host_type_regex` for a case, if it's the same as `host_type_regex` in the top `index.yaml` - that's the default.

2019-11-15 13:34 UTC, spbnick commented on tests/test_integration_multihost_types.py
> +        self.assertKpetSrcMatchesNoneOfTwoSuites(assets_path)
Could you make this a separate commit?

2019-11-15 13:35 UTC, spbnick commented on tests/test_integration_misc.py
> +                      host_type_regex: normal
So, could you remove it?

2019-11-15 14:09 UTC, spbnick commented
LGTM!
@cki-bot, please test!

2019-11-18 07:40 UTC, emanchado commented
Just had a look at the test results, and there is an architecture (or two, in the last link) that fails, but the rest pass. They aren't always the same arch. I guess that means it's not my patch that's failing?

2019-11-18 10:08 UTC, spbnick commented
Shouldn't be related. Merging!
Thank you, Esteban :)

2019-11-18 10:08 UTC, merged