Clean up validation error messages
cki-project/kpet-archived pull request #124
Opened 2019-11-21 10:33 UTC by emanchado

In validation code we often throw exceptions inside exception
handlers, which makes Python report the exception like a problem while
handling the original exception. That's not good, first because it
looks like a bug in our code, and second because the validation error
output on the console becomes pretty big and it's very confusing to
read. So, explicitly clear up all references to the exception
"context" (by using "from None" at the end of the raise statement) for
all exceptions thrown inside a exception handler.

Ref. FASTMOVING-1456

2019-11-21 11:14 UTC, spbnick requested changes
Yes, this was half-backed, and I simply didn't have time to go and improve it.
However, instead of fighting the Python's exception chaining, why not use it instead?
Just drop the `kpet.schema.Invalid.__str__()` method altogether, catch all exceptions in `kpet.main()` and print them using the method in the former, then exit with `1`.

2019-11-21 11:21 UTC, spbnick commented
Oh, and print the exception normally, if `-d/--debug` was specified. Drop backtrace disabling at the same time.

2019-11-22 09:49 UTC, spbnick approved these changes
LGTM! Thanks, Esteban :)

2019-11-22 09:49 UTC, spbnick commented
Could you please fix the pylint complaints?

2019-11-25 14:39 UTC, spbnick approved these changes
Looks good! Thanks a lot, Esteban :)!

2019-11-25 14:39 UTC, spbnick commented
@cki-bot, please test!

2019-11-26 07:01 UTC, emanchado commented
Only s390x failing, should we assume it's fine?

2019-11-26 09:30 UTC, spbnick commented
The failures seem unrelated. Merging!

2019-11-26 09:31 UTC, merged