Add a "maintainers" field to test cases
cki-project/kpet-archived pull request #126
Opened 2019-11-28 09:38 UTC by emanchado

Add test case-level maintainers, and expose that to the Beaker XML
templates.

Ref. FASTMOVING-1438

2019-11-28 09:50 UTC, spbnick requested changes

2019-11-28 09:50 UTC, spbnick commented on kpet/data.py
> +                    maintainers=List(String(), min_len=1),
I think allowing specifying an empty list of maintainers makes it less cumbersome to edit or generate test cases. The field is optional anyway. Could you make it just `List(String())`?

2019-11-28 11:49 UTC, spbnick approved these changes
LGTM!

2019-11-28 11:50 UTC, spbnick commented
@cki-bot, please test!

2019-11-29 08:57 UTC, emanchado commented
Timeout when testing x86_64, everything else passed. Probably unrelated to my change?

2019-11-29 10:20 UTC, spbnick commented
Yeah, shouldn't be related. Merging!
Thanks, Esteban :)

2019-11-29 10:20 UTC, merged