Rename hostRequires_list to host_requires_list
cki-project/kpet-archived pull request #140
Opened 2020-02-07 12:06 UTC by emanchado

Although it does hold a list of "hostRequires", it's a bit ugly that
we end up with a variable that has both mixedCase and snake_case in
the same name. So, default to the normal Python convention and use
"host_requires_list" for the variable.

Ref. FASTMOVING-1612

2020-02-10 08:49 UTC, spbnick commented
This looks good, thank you!

However, you gotta take care of transitioning kpet-db to the new name smoothly. So instead start with exposing both the old name and the new name, submit an MR to kpet-db, which switches over to the new name, then when that's merged, submit another one to kpet, which removes the old name.

2020-02-10 08:50 UTC, spbnick requested changes
Please see the previous comment for requested changes.

2020-02-10 09:51 UTC, emanchado commented
Oops, my bad. I thought of it, but then wrongly thought that it was just internal and it wasn't a problem. Oh well. See the update.

2020-02-13 09:52 UTC, spbnick requested changes
Looks good, I have just two minor requests :)

2020-02-13 09:52 UTC, spbnick commented on kpet/run.py
> +        # For compatibility. Remove when kpet-db is updated.
Can you add `TODO: ` in front of this comment? Then it will be easy to find.

2020-02-13 09:52 UTC, spbnick commented on kpet/run.py
> +        self.hostRequires_list = self.host_requires_list
Can you move this line, along with the comment to be together with the `self.host_requires_list` assignment?

2020-02-13 10:28 UTC, emanchado commented
@cki-bot: test!

2020-02-13 12:00 UTC, emanchado commented
See #141 for the test results.

2020-02-17 08:22 UTC, emanchado commented
#141 was merged, so no sense in keeping this anymore

2020-02-17 08:22 UTC, closed without merging