ensure waived tasks are at the end of the job
cki-project/kpet-archived pull request #33
Opened 2019-02-05 12:53 UTC by wizardofoz123

Signed-off-by: Jakub Racek <jracek@redhat.com>

2019-02-05 17:52 UTC, agustinhenze approved these changes

2019-02-06 08:18 UTC, agustinhenze requested changes
Actually I regret :stuck_out_tongue:. I think this approach is mixing the output with the definition of the tests. Is binding the output with the input and last but not least the code is really complicated because you need to parse the xml and so far kpet didn't know anything about xml.
What about putting the keyword `waived` in the layout def and then send it as a variable to jinja?

2019-02-06 09:17 UTC, spbnick commented
I agree with @agustinhenze, we shouldn't really be parsing the Beaker XML for this. We would need to instead store the waived state in the suite's JSON description and go from there.

However, that would also mean that we would need to modify the Beaker XML based on that value. Probably have some "escape hatch" in Jinja code for each test suite, to allow the Python code to insert arbitrary XML. That could then be used to insert the waived state XML, as well as (later) test maintainer information for sending out failure reports to maintainers.

Another result of this approach is the order of the tests would be changing when we remove waived state from them, possibly introducing its own problems, and that would be just when we thought they're stable and they would start affecting results. So, unless we really see any interference from waived tests, let's withhold this change in principle, not just this implementation.

Let's instead focus on adding actual waived tests to kpet-db and looking at how they work.

2019-02-07 18:44 UTC, wizardofoz123 commented
https://github.com/CKI-project/kpet/pull/35

2019-02-07 18:44 UTC, closed without merging