Remove legacy schema
cki-project/kpet-archived pull request #61
Opened 2019-03-26 08:31 UTC by wizardofoz123

This is an attempt to remove the old (legacy) db schema from kpet.

2019-03-26 10:14 UTC, spbnick requested changes
Looks great, thanks a lot, Jakub! Requesting a couple tweaks only.

2019-03-26 10:14 UTC, spbnick commented on kpet/schema.py
> -
Please don't remove the Succession schema implementation, we'll keep using it :smile:!

2019-03-26 10:14 UTC, spbnick commented on tests/assets/db/invalid/semantics/missing_case/suite.yaml
> -      case_name: case2
We need to remove this database and the associated test case altogether as they no longer apply. The test should have a TODO about this.

2019-03-26 11:49 UTC, wizardofoz123 commented
@cki-bot: test this, bot!

2019-03-27 11:47 UTC, spbnick approved these changes
Looks good! Thank you, Jakub :)

2019-03-27 11:48 UTC, merged

2019-03-27 11:51 UTC, wizardofoz123 commented
Thank you too Nick, all those suggested tweaks were valuable. :)